import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=" bg-blue-200 h-screen flex items-center justify-center">
        <main className=" bg-gray-800 h-4/5 w-[30%] rounded-xl px-8 py-8">
          {children}
        </main>
        <Toaster />
      </body>
    </html>
  );
}
